### ISSUE TITLE
Asset > POST /organizations/{org}/file - File not available for download

### ISSUE THREAD

**Issue by t0mj** [tallyfy/api-support#1]
Hey there, just wanted to report an issue I'm running into with the file api. 

I am trying to upload a test txt file. If I upload through the UI, I can download it just fine. When using the API through postman I POST the upload and then make the required PUT to api/organizations/{org}/runs/{step_id}/tasks/{id} with the file data. The file appears in the UI but is not available for download and throws a 500 server error.

I've tried making this same request to requestbin and I see the file data. Is there anything I'm doing wrong or that needs to be enabled for me to upload via the API? Thought I would start here as I tried a couple of ways and with different processes and was unable to have a downloadable file.

Here's the two requests from postman, let me know if I can provide any other context or info:
<img width="1093" alt="Screen Shot 2020-11-18 at 10 57 45 AM" src="https://user-images.githubusercontent.com/7049067/99562471-c0ff0c80-298d-11eb-99bb-cd680c5a7478.png">
<img width="854" alt="Screen Shot 2020-11-18 at 11 01 21 AM" src="https://user-images.githubusercontent.com/7049067/99562477-c2c8d000-298d-11eb-9a63-e6d24d67a247.png">

Requestbin:
![image](https://user-images.githubusercontent.com/7049067/99562900-47b3e980-298e-11eb-9300-bc03b907c7b3.png)

**Comment by go4mahmood** [comment]
Hello @t0mj, thank you for posting the query!

The steps that you followed to upload the file, and attach it to a task, are correct except for one small bit - the value of `subject_type` here needs to be `Run` (instead of `run`).

<img width="1093" alt="Screen Shot 2020-11-18 at 10 57 45 AM" src="https://user-images.githubusercontent.com/7049067/99562471-c0ff0c80-298d-11eb-99bb-cd680c5a7478.png">

You can follow the rest of the steps and correctly upload and attach the file to a task.

For more info, you can check this out: https://support.tallyfy.com/article/443-rest-api-how-do-i-upload-or-attach-a-file-asset-to-a-task-field

**Comment by amitkoth** [comment]
Thanks @go4mahmood - hopefully that does the trick @t0mj ?

**Comment by t0mj** [comment]
That worked! Thank you guys sorry I cant believe I missed that! Appreciate the quick response and link to the article.
